[package]
name = "lazycsv"
version = "0.1.0"
edition = "2021"

[dependencies]
memchr = "2.7.4"
thiserror = { version = "2.0.11", default-features = false }

[dev-dependencies]
criterion = "0.5.1"
csv = "1.3.1"
memmap2 = "0.9.5"

[[bench]]
name = "single_thread"
harness = false
