name: check
on: push

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --no-deps -- -D warnings
      - run: cargo test

        # no_std, no_alloc
      - run: cargo clippy --no-default-features --no-deps -- -D warnings
      - run: cargo test --no-default-features

        # no_std
      - run: cargo clippy --no-default-features -F alloc --no-deps -- -D warnings
      - run: cargo test --no-default-features -F alloc

        # all features
      - run: cargo clippy --all-features --no-deps -- -D warnings
      - run: cargo test --all-features
